-- Remediation-M4 combined-generator vectors. Expected values are deliberately
-- literal: changing an algorithm requires a reviewed version/vector update.
return {
  { id = "CASUAL_01", seed = "M4 CASUAL 01", profile = "casual" },
  { id = "CASUAL_02", seed = "M4 CASUAL 02", profile = "casual" },
  { id = "CASUAL_03", seed = "M4 CASUAL 03", profile = "casual" },
  { id = "CASUAL_04", seed = "M4 CASUAL 04", profile = "casual" },
  { id = "CASUAL_05", seed = "M4 CASUAL 05", profile = "casual" },

  { id = "STANDARD_01", seed = "M4 STANDARD 01", profile = "standard" },
  { id = "STANDARD_02", seed = "M4 STANDARD 02", profile = "standard" },
  { id = "STANDARD_03", seed = "M4 STANDARD 03", profile = "standard" },
  { id = "STANDARD_04", seed = "M4 STANDARD 04", profile = "standard" },
  { id = "STANDARD_05", seed = "M4 STANDARD 05", profile = "standard" },
  { id = "STANDARD_06", seed = "M4 STANDARD 06", profile = "standard" },

  { id = "CHAOS_01", seed = "M4 CHAOS 01", profile = "chaos" },
  { id = "CHAOS_02", seed = "M4 CHAOS 02", profile = "chaos" },
  { id = "CHAOS_03", seed = "M4 CHAOS 03", profile = "chaos" },
  { id = "CHAOS_04", seed = "M4 CHAOS 04", profile = "chaos" },
  { id = "CHAOS_05", seed = "M4 CHAOS 05", profile = "chaos" },

  {
    id = "CUSTOM_TRIAD_THEMED",
    seed = "M4 CUSTOM TRIAD",
    profile = "standard",
    overrides = {
      starters = "type_triad",
      trainer_pokemon = "type_themed",
      wild_pokemon = "area_slots",
      wild_levels = "scaled",
      static_levels = "scaled",
      gift_levels = "fixed_15",
      in_game_trades = "received",
      prize_levels = "fixed_15",
      prize_prices = "by_strength",
    },
  },
  {
    id = "CUSTOM_BLUE_CHAOS",
    seed = "M4 CUSTOM BLUE",
    profile = "chaos",
    sourceOverrides = { gameVersion = "blue" },
  },
  {
    id = "CUSTOM_GLOBAL_SCALED",
    seed = "M4 GLOBAL SCALED",
    profile = "standard",
    overrides = {
      trainer_pokemon = "global_map",
      trainer_levels = "progressive",
      wild_levels = "scaled",
      static_levels = "scaled",
      gift_levels = "scaled",
      prize_levels = "scaled",
      prize_prices = "by_strength",
    },
  },
  {
    id = "CUSTOM_WILD_ONLY",
    seed = "M4 WILD ONLY",
    profile = "standard",
    overrides = {
      starters = "off",
      static_pokemon = "off",
      gift_pokemon = "off",
      in_game_trades = "off",
      game_corner_pokemon = "off",
      trainer_pokemon = "off",
    },
  },
  {
    id = "CUSTOM_NO_WILD",
    seed = "M4 NO WILD",
    profile = "standard",
    overrides = {
      wild_pokemon = "off",
      fishing = "vanilla",
      catchability_guard = "off",
    },
  },
  {
    id = "CUSTOM_EXCLUDE_THEMED",
    seed = "M4 EXCLUDE THEMED",
    profile = "standard",
    overrides = {
      legendaries = "exclude",
      trainer_pokemon = "type_themed",
      boss_trainers = "include",
      similar_strength = "same_stage",
    },
  },
  {
    id = "CUSTOM_ALLOW_DUPES",
    seed = "M4 ALLOW DUPES",
    profile = "standard",
    overrides = {
      duplicate_policy = "allow",
      legendaries = "allow",
      gift_uniqueness = "allow",
      trade_fairness = "any",
      trade_evolution_safety = "off",
      prize_prices = "random_25",
      party_size = "random_1_6",
      similar_strength = "bst_100",
    },
  },
  {
    id = "CUSTOM_ALL_OFF",
    seed = "M4 ALL OFF",
    profile = "standard",
    overrides = {
      wild_pokemon = "off",
      fishing = "vanilla",
      starters = "off",
      static_pokemon = "off",
      gift_pokemon = "off",
      in_game_trades = "off",
      game_corner_pokemon = "off",
      trainer_pokemon = "off",
      catchability_guard = "off",
    },
  },

  -- Round-3 milestone 2: enabled item and mechanics combinations use the
  -- complete settings surface and the realistic sources in the harness.
  {
    id = "R3_ITEMS_CLOSED",
    seed = "R3 ITEMS CLOSED",
    profile = "standard",
    round3 = true,
    overrides = { non_key_items = "shuffled" },
  },
  {
    id = "R3_ITEMS_PROGRESSION",
    seed = "R3 ITEMS PROGRESSION",
    profile = "standard",
    round3 = true,
    overrides = {
      non_key_items = "mixed", tms = "mixed", hms = "mixed",
      key_items = "mixed", badges = "mixed", hidden_items = "mixed",
      ensure_beatable = "on",
    },
  },
  {
    id = "R3_SHOPS_RANDOM",
    seed = "R3 SHOPS RANDOM",
    profile = "standard",
    round3 = true,
    overrides = {
      tms = "shuffled", shops = "randomized", shop_prices = "random",
    },
  },
  {
    id = "R3_STATS_TYPES",
    seed = "R3 STATS TYPES",
    profile = "standard",
    round3 = true,
    overrides = {
      base_stats = "redistributed", stat_family_consistency = "on",
      pokemon_types = "randomized", type_family_consistency = "on",
    },
  },
  {
    id = "R3_MOVESETS_COMPAT",
    seed = "R3 MOVESETS COMPAT",
    profile = "standard",
    round3 = true,
    overrides = {
      pokemon_movesets = "randomized", early_damage = "on",
      learnset_levels = "shuffled", tmhm_compatibility = "shuffled",
    },
  },
  {
    id = "R3_EVOLUTIONS",
    seed = "R3 EVOLUTIONS",
    profile = "standard",
    round3 = true,
    overrides = {
      evolutions = "preserve_stages", evolution_repeats = "avoid",
      evolution_trade_safety = "fixed_37",
    },
  },
  {
    id = "R3_MOVE_DATA",
    seed = "R3 MOVE DATA",
    profile = "standard",
    round3 = true,
    overrides = {
      move_types = "shuffled", move_data = "balanced", move_safety = "on",
    },
  },
  {
    id = "R3_ALL_ENABLED",
    seed = "R3 ALL ENABLED",
    profile = "standard",
    round3 = true,
    overrides = {
      non_key_items = "mixed", tms = "mixed", hms = "mixed",
      key_items = "mixed", badges = "mixed", hidden_items = "mixed",
      ensure_beatable = "on", shops = "randomized", shop_prices = "cheap",
      base_stats = "full_random", stat_family_consistency = "off",
      evolutions = "full_random", evolution_repeats = "avoid",
      evolution_trade_safety = "random_30_40",
      pokemon_types = "randomized", type_family_consistency = "on",
      pokemon_movesets = "type_aware", early_damage = "on",
      learnset_levels = "shuffled", tmhm_compatibility = "shuffled",
      move_types = "randomized", move_data = "full_random",
      move_safety = "on",
    },
  },
}
