-- Explicit updater for the literal combined-generator golden expectations.
-- Run from the repository root with Lua 5.1 after reviewing vector changes.
local Harness = assert(loadfile("tests/generator_harness.lua"))()
local Vectors = assert(loadfile("tests/generator_golden_vectors.lua"))()
local GoldenRequest = assert(loadfile("tests/generator_golden_request.lua"))()
local keys = Harness.Contracts.mappingKeys()

local function quote(value)
  return string.format("%q", tostring(value))
end

local function array(values)
  local output = {}
  for index, value in ipairs(values or {}) do output[index] = quote(value) end
  return "{ " .. table.concat(output, ", ") .. " }"
end

local lines = {
  "-- Generated by tools/update-generator-golden.lua under Lua 5.1.",
  "-- Review every changed literal before accepting an algorithm update.",
  "return {",
}

for _, vector in ipairs(Vectors) do
  local request = GoldenRequest(Harness, vector)
  local result, err = Harness.Generator.generate(request)
  assert(result, err and err.message)
  assert(Harness.Contracts.validateGenerationResult(result))
  local warnings = Harness.warningCodes(result)
  local validation = assert(result.diagnostics.validation)

  lines[#lines + 1] = "  " .. vector.id .. " = {"
  lines[#lines + 1] = "    input = " .. quote(Harness.hash(request)) .. ","
  lines[#lines + 1] = "    manifest = "
    .. quote(Harness.hash(request.species)) .. ","
  lines[#lines + 1] = "    sources = "
    .. quote(Harness.hash(request.sources)) .. ","
  lines[#lines + 1] = "    mappings = {"
  for _, key in ipairs(keys) do
    lines[#lines + 1] = ("      %s = %s,"):format(
      key, quote(Harness.hash(result.mappings[key])))
  end
  lines[#lines + 1] = "    },"
  lines[#lines + 1] = "    combined = "
    .. quote(Harness.hash(result.mappings)) .. ","
  lines[#lines + 1] = "    warnings = " .. array(warnings) .. ","
  lines[#lines + 1] = "    fallback = "
    .. tostring(result.diagnostics.fallbackCount) .. ","
  lines[#lines + 1] = ("    validation = { %d, %d, %d, %d },"):format(
    validation.repairSwaps,
    validation.reachableSpecies,
    validation.mappingEntries,
    #Harness.Canonical.encode(result.mappings))
  lines[#lines + 1] = "  },"
end
lines[#lines + 1] = "}"
lines[#lines + 1] = ""

local outputPath = "tests/generator_golden_expected.lua"
local file, openError = io.open(outputPath, "wb")
assert(file, openError)
file:write(table.concat(lines, "\n"))
file:close()
io.write(("updated %s (%d vectors, %d mapping buckets)\n")
  :format(outputPath, #Vectors, #keys))
