-- Script-command item sources not represented by map object/hidden-item data.
-- Direct-function gifts are deliberately handled separately by runtime map
-- adapters; this catalog is for the engine's public give_item command.
return {
  { id = "oak_poke_balls", mapId = "OAKS_LAB", item = "POKE_BALL" },
  { id = "oaks_parcel", mapId = "VIRIDIAN_MART", item = "OAKS_PARCEL" },
  { id = "town_map", mapId = "REDS_HOUSE_1F", item = "TOWN_MAP" },
  { id = "ss_ticket", mapId = "BILLS_HOUSE", item = "S_S_TICKET" },
  { id = "hm_cut", mapId = "SS_ANNE_CAPTAINS_ROOM", item = "HM_CUT" },
  { id = "poke_flute", mapId = "POKEMON_TOWER_7F", item = "POKE_FLUTE" },
  { id = "hm_surf", mapId = "SAFARI_ZONE_SECRET_HOUSE", item = "HM_SURF" },
  { id = "hm_strength", mapId = "WARDENS_HOUSE", item = "HM_STRENGTH" },
  { id = "master_ball", mapId = "SILPH_CO_11F", item = "MASTER_BALL" },
  { id = "bike_voucher", mapId = "POKEMON_FAN_CLUB", item = "BIKE_VOUCHER" },
  { id = "old_rod", mapId = "VERMILION_OLD_ROD_HOUSE", item = "OLD_ROD" },
  { id = "good_rod", mapId = "FUCHSIA_GOOD_ROD_HOUSE", item = "GOOD_ROD" },
  { id = "super_rod", mapId = "ROUTE_12_SUPER_ROD_HOUSE", item = "SUPER_ROD" },
  { id = "tm_dig", mapId = "CERULEAN_CITY", item = "TM_DIG" },

  { id = "hm_flash", mapId = "ROUTE_2_GATE", item = "HM_FLASH",
    talkKey = "TEXT_ROUTE2GATE_OAKS_AIDE", flag = "EVENT_GOT_HM_FLASH", command = false },
  { id = "itemfinder", mapId = "ROUTE_11_GATE_2F", item = "ITEMFINDER",
    talkKey = "TEXT_ROUTE11GATE2F_OAKS_AIDE", flag = "EVENT_GOT_ITEMFINDER", command = false },
  { id = "exp_all", mapId = "ROUTE_15_GATE_2F", item = "EXP_ALL",
    talkKey = "TEXT_ROUTE15GATE2F_OAKS_AIDE", flag = "EVENT_GOT_EXP_ALL", command = false },
  { id = "coin_case", mapId = "CELADON_DINER", item = "COIN_CASE",
    talkKey = "TEXT_CELADONDINER_GYM_GUIDE", flag = "EVENT_GOT_COIN_CASE", command = false },
  { id = "tm_counter", mapId = "CELADON_MART_3F", item = "TM_COUNTER",
    talkKey = "TEXT_CELADONMART3F_CLERK", flag = "EVENT_GOT_TM18", command = false },
  { id = "tm_swift", mapId = "ROUTE_12_GATE_2F", item = "TM_SWIFT",
    talkKey = "TEXT_ROUTE12GATE2F_BRUNETTE_GIRL", flag = "EVENT_GOT_TM39", command = false },
  { id = "tm_softboiled", mapId = "CELADON_CITY", item = "TM_SOFTBOILED",
    talkKey = "TEXT_CELADONCITY_GRAMPS3", flag = "EVENT_GOT_TM41", command = false },
  { id = "tm_metronome", mapId = "CINNABAR_LAB_METRONOME_ROOM", item = "TM_METRONOME",
    talkKey = "TEXT_CINNABARLABMETRONOMEROOM_SCIENTIST1", flag = "EVENT_GOT_TM35", command = false },
  { id = "tm_dream_eater", mapId = "VIRIDIAN_CITY", item = "TM_DREAM_EATER",
    talkKey = "TEXT_VIRIDIANCITY_FISHER", flag = "EVENT_GOT_TM42", command = false },
  { id = "tm_selfdestruct", mapId = "SILPH_CO_2F", item = "TM_SELFDESTRUCT",
    talkKey = "TEXT_SILPHCO2F_SILPH_WORKER_F", flag = "EVENT_GOT_TM36", command = false },
  { id = "route_1_potion", mapId = "ROUTE_1", item = "POTION",
    talkKey = "TEXT_ROUTE1_YOUNGSTER1", flag = "EVENT_GOT_POTION_SAMPLE", command = false },
  { id = "tm_mimic", mapId = "COPYCATS_HOUSE_2F", item = "TM_MIMIC",
    talkKey = "TEXT_COPYCATSHOUSE2F_COPYCAT", flag = "EVENT_GOT_TM31", command = false },
  { id = "tm_psychic", mapId = "MR_PSYCHICS_HOUSE", item = "TM_PSYCHIC_M",
    talkKey = "TEXT_MRPSYCHICSHOUSE_MR_PSYCHIC", flag = "EVENT_GOT_TM29", command = false },
  { id = "hm_fly", mapId = "ROUTE_16_FLY_HOUSE", item = "HM_FLY",
    talkKey = "TEXT_ROUTE16FLYHOUSE_BRUNETTE_GIRL", flag = "EVENT_GOT_HM02", command = false },
  { id = "tm_ice_beam", mapId = "CELADON_MART_ROOF", item = "TM_ICE_BEAM",
    talkKey = "TEXT_CELADONMARTROOF_LITTLE_GIRL", flag = "EVENT_GOT_TM13", command = false },
  { id = "tm_rock_slide", mapId = "CELADON_MART_ROOF", item = "TM_ROCK_SLIDE",
    talkKey = "TEXT_CELADONMARTROOF_LITTLE_GIRL", flag = "EVENT_GOT_TM48", command = false },
  { id = "tm_tri_attack", mapId = "CELADON_MART_ROOF", item = "TM_TRI_ATTACK",
    talkKey = "TEXT_CELADONMARTROOF_LITTLE_GIRL", flag = "EVENT_GOT_TM49", command = false },
  { id = "nugget_bridge", mapId = "ROUTE_24", item = "NUGGET",
    talkKey = "TEXT_ROUTE24_COOLTRAINER_M1", flag = "EVENT_GOT_NUGGET", command = false },
  { id = "bicycle", mapId = "BIKE_SHOP", item = "BICYCLE",
    talkKey = "TEXT_BIKESHOP_CLERK", flag = "EVENT_GOT_BICYCLE", command = false },
  { id = "dome_fossil", mapId = "MT_MOON_B2F", item = "DOME_FOSSIL",
    talkKey = "TEXT_MTMOONB2F_DOME_FOSSIL", flag = "EVENT_GOT_DOME_FOSSIL", command = false },
  { id = "helix_fossil", mapId = "MT_MOON_B2F", item = "HELIX_FOSSIL",
    talkKey = "TEXT_MTMOONB2F_HELIX_FOSSIL", flag = "EVENT_GOT_HELIX_FOSSIL", command = false },
  { id = "old_amber", mapId = "MUSEUM_1F", item = "OLD_AMBER",
    talkKey = "TEXT_MUSEUM1F_OLD_AMBER", flag = "EVENT_GOT_OLD_AMBER", command = false },

  -- Badges are inventory-backed item ids in Gen1Recomp, but their vanilla
  -- locations are battle rewards rather than ordinary give_item commands.
  -- Keeping them in this catalog lets the existing post-battle exchange
  -- adapter project shuffled badges without patching the engine.
  { id = "brock_badge", mapId = "PEWTER_GYM", item = "BOULDERBADGE",
    flag = "EVENT_BEAT_BROCK", battle = true, command = false, badge = true },
  { id = "misty_badge", mapId = "CERULEAN_GYM", item = "CASCADEBADGE",
    flag = "EVENT_BEAT_MISTY", battle = true, command = false, badge = true },
  { id = "surge_badge", mapId = "VERMILION_GYM", item = "THUNDERBADGE",
    flag = "EVENT_BEAT_LT_SURGE", battle = true, command = false, badge = true },
  { id = "erika_badge", mapId = "CELADON_GYM", item = "RAINBOWBADGE",
    flag = "EVENT_BEAT_ERIKA", battle = true, command = false, badge = true },
  { id = "koga_badge", mapId = "FUCHSIA_GYM", item = "SOULBADGE",
    flag = "EVENT_BEAT_KOGA", battle = true, command = false, badge = true },
  { id = "sabrina_badge", mapId = "SAFFRON_GYM", item = "MARSHBADGE",
    flag = "EVENT_BEAT_SABRINA", battle = true, command = false, badge = true },
  { id = "blaine_badge", mapId = "CINNABAR_GYM", item = "VOLCANOBADGE",
    flag = "EVENT_BEAT_BLAINE", battle = true, command = false, badge = true },
  { id = "giovanni_badge", mapId = "VIRIDIAN_GYM", item = "EARTHBADGE",
    flag = "EVENT_BEAT_GIOVANNI", battle = true, command = false, badge = true },

  { id = "brock_tm", mapId = "PEWTER_GYM", item = "TM_BIDE",
    flag = "EVENT_BEAT_BROCK", battle = true, command = false },
  { id = "misty_tm", mapId = "CERULEAN_GYM", item = "TM_BUBBLEBEAM",
    flag = "EVENT_BEAT_MISTY", battle = true, command = false },
  { id = "surge_tm", mapId = "VERMILION_GYM", item = "TM_THUNDERBOLT",
    flag = "EVENT_BEAT_LT_SURGE", battle = true, command = false },
  { id = "erika_tm", mapId = "CELADON_GYM", item = "TM_MEGA_DRAIN",
    flag = "EVENT_BEAT_ERIKA", battle = true, command = false },
  { id = "koga_tm", mapId = "FUCHSIA_GYM", item = "TM_TOXIC",
    flag = "EVENT_BEAT_KOGA", battle = true, command = false },
  { id = "sabrina_tm", mapId = "SAFFRON_GYM", item = "TM_PSYWAVE",
    flag = "EVENT_BEAT_SABRINA", battle = true, command = false },
  { id = "blaine_tm", mapId = "CINNABAR_GYM", item = "TM_FIRE_BLAST",
    flag = "EVENT_BEAT_BLAINE", battle = true, command = false },
  { id = "giovanni_tm", mapId = "VIRIDIAN_GYM", item = "TM_FISSURE",
    flag = "EVENT_BEAT_GIOVANNI", battle = true, command = false },
}
